version: "3"
services:
  ssh-reverse:
    container_name: ssh-reverse
    build:
      context: .
      dockerfile: dockerfile
      #dockerfileにproxyアドレスを引数として渡す
      #args:
      #  - http_tmp=$http_proxy
      #  - https_tmp=$https_proxy
    
    privileged: true
    tty: true

    #コンテナ内でsystemdを起動
    command: /sbin/init

    #proxyアドレスを読込む
    env_file:
      - .env
    ports:
      #SSHポート番号
      - "22:22"
      #外部に公開するsshポート番号
      - "49201:49201"
      - "49202:49202"
      - "49203:49203"
      - "49204:49204"
      - "49205:49205"